# review-skill.ps1
# Purpose: Main orchestrator for skill review
# Usage: .\review-skill.ps1 <skill-name> [-AutoFix]

param(
    [Parameter(Mandatory=$true)][string]$SkillName,
    [switch]$AutoFix
)

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$skillsDir = Split-Path -Parent (Split-Path -Parent $scriptDir)
$skillPath = Join-Path $skillsDir $SkillName

# Report directory from project root
$projectRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $scriptDir))
$reportDir = Join-Path $projectRoot "docs\skills\reviews"
New-Item -ItemType Directory -Path $reportDir -Force | Out-Null

$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$reportFile = Join-Path $reportDir "$SkillName-review-$timestamp.md"

Write-Host "================================================"
Write-Host "Skill Review: $SkillName"
Write-Host "================================================"
Write-Host ""

$score = 100
$criticalIssues = 0
$majorIssues = 0
$minorIssues = 0

# Phase 1: Structure
Write-Host "[1/4] Structure Validation..."
$structOutput = & "$scriptDir\validate-structure.ps1" $skillPath
Write-Host $structOutput

if ($structOutput -match "Total Penalty: (\d+)") {
    $penalty = [int]$matches[1]
    $score -= $penalty
}

# Count issues by severity
$criticalIssues = ([regex]::Matches($structOutput, "-20 points")).Count
$majorIssues = ([regex]::Matches($structOutput, "-5 points")).Count
$minorIssues = ([regex]::Matches($structOutput, "-1 point")).Count

Write-Host ""

# Phase 2-4: Additional validations would go here

Write-Host "================================================"
Write-Host "Final Score: $score/100"

# Generate review report
$status = if ($score -ge 70) { "✅ PASSED" } else { "❌ FAILED" }
$reviewDate = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

$recommendations = if ($score -ge 90) {
    "✅ Excellent! This skill is production-ready with no significant issues."
} elseif ($score -ge 70) {
    "✅ Good! Address minor issues to improve quality further."
} else {
    @"
❌ This skill requires fixes before proceeding to testing.

**Action Items:**
1. Fix all critical issues (structure, YAML)
2. Address major issues (content completeness)
3. Re-run review to verify improvements
"@
}

$nextSteps = if ($score -ge 70) {
    @"
- Proceed to testing with skill-tester
- Commit skill to repository
- Update skill inventory
"@
} else {
    @"
- Fix identified issues
- Re-run skill-reviewer
- Do not proceed to testing until score ≥ 70
"@
}

$reportContent = @"
# Skill Review Report

## Summary

| Field | Value |
|-------|-------|
| **Skill Name** | ``$SkillName`` |
| **Review Date** | $reviewDate |
| **Final Score** | $score/100 |
| **Status** | $status |

---

## Issue Summary

- **Critical Issues:** $criticalIssues
- **Major Issues:** $majorIssues
- **Minor Issues:** $minorIssues

---

## Validation Results

### Structure Validation

``````
$structOutput
``````

---

## Recommendations

$recommendations

---

## Next Steps

$nextSteps

---

**Report Location:** ``$reportFile``

**Generated by:** skill-reviewer v1.0
"@

$reportContent | Out-File -FilePath $reportFile -Encoding UTF8

if ($score -ge 70) {
    Write-Host "Status: ✅ PASSED" -ForegroundColor Green
    Write-Host ""
    Write-Host "Report saved to: $reportFile"
    exit 0
} else {
    Write-Host "Status: ❌ FAILED" -ForegroundColor Red
    Write-Host ""
    Write-Host "Report saved to: $reportFile"
    exit 1
}
