#!/bin/bash
# review-skill.sh
# Purpose: Main orchestrator for skill review
# Usage: ./review-skill.sh <skill-name> [--auto-fix]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILLS_DIR="$(dirname "$SCRIPT_DIR")/../.."
SKILL_NAME="$1"
SKILL_PATH="$SKILLS_DIR/$SKILL_NAME"
AUTO_FIX=false

# Report directory from project root
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
REPORT_DIR="$PROJECT_ROOT/docs/skills/reviews"
mkdir -p "$REPORT_DIR"

TIMESTAMP=$(date '+%Y%m%d-%H%M%S')
REPORT_FILE="$REPORT_DIR/${SKILL_NAME}-review-${TIMESTAMP}.md"

if [ "${2:-}" = "--auto-fix" ]; then
    AUTO_FIX=true
fi

echo "================================================"
echo "Skill Review: $SKILL_NAME"
echo "================================================"
echo ""

SCORE=100
CRITICAL_ISSUES=0
MAJOR_ISSUES=0
MINOR_ISSUES=0

# Phase 1: Structure
echo "[1/4] Structure Validation..."
"$SCRIPT_DIR/validate-structure.sh" "$SKILL_PATH" | tee /tmp/struct.out
STRUCT_PENALTY=$(grep "Total Penalty:" /tmp/struct.out | awk '{print $3}')
SCORE=$((SCORE - STRUCT_PENALTY))

# Count issues by checking penalties (simplified)
if grep -q "\-20 points" /tmp/struct.out; then
    CRITICAL_ISSUES=$((CRITICAL_ISSUES + $(grep -c "\-20 points" /tmp/struct.out || echo 0)))
fi
if grep -q "\-5 points" /tmp/struct.out; then
    MAJOR_ISSUES=$((MAJOR_ISSUES + $(grep -c "\-5 points" /tmp/struct.out || echo 0)))
fi
if grep -q "\-1 point" /tmp/struct.out; then
    MINOR_ISSUES=$((MINOR_ISSUES + $(grep -c "\-1 point" /tmp/struct.out || echo 0)))
fi

echo ""

# Phase 2-4: Additional validations would go here
# For now, simplified version

echo "================================================"
echo "Final Score: $SCORE/100"

# Generate review report
cat > "$REPORT_FILE" << EOF
# Skill Review Report

## Summary

| Field | Value |
|-------|-------|
| **Skill Name** | \`$SKILL_NAME\` |
| **Review Date** | $(date '+%Y-%m-%d %H:%M:%S') |
| **Final Score** | $SCORE/100 |
| **Status** | $([ $SCORE -ge 70 ] && echo "✅ PASSED" || echo "❌ FAILED") |

---

## Issue Summary

- **Critical Issues:** $CRITICAL_ISSUES
- **Major Issues:** $MAJOR_ISSUES
- **Minor Issues:** $MINOR_ISSUES

---

## Validation Results

### Structure Validation

\`\`\`
$(cat /tmp/struct.out)
\`\`\`

---

## Recommendations

$(if [ $SCORE -ge 90 ]; then
    echo "✅ Excellent! This skill is production-ready with no significant issues."
elif [ $SCORE -ge 70 ]; then
    echo "✅ Good! Address minor issues to improve quality further."
else
    echo "❌ This skill requires fixes before proceeding to testing."
    echo ""
    echo "**Action Items:**"
    echo "1. Fix all critical issues (structure, YAML)"
    echo "2. Address major issues (content completeness)"
    echo "3. Re-run review to verify improvements"
fi)

---

## Next Steps

$(if [ $SCORE -ge 70 ]; then
    echo "- Proceed to testing with skill-tester"
    echo "- Commit skill to repository"
    echo "- Update skill inventory"
else
    echo "- Fix identified issues"
    echo "- Re-run skill-reviewer"
    echo "- Do not proceed to testing until score ≥ 70"
fi)

---

**Report Location:** \`$REPORT_FILE\`

**Generated by:** skill-reviewer v1.0
EOF

if [ $SCORE -ge 70 ]; then
    echo "Status: ✅ PASSED"
    echo ""
    echo "Report saved to: $REPORT_FILE"
    exit 0
else
    echo "Status: ❌ FAILED"
    echo ""
    echo "Report saved to: $REPORT_FILE"
    exit 1
fi
